# fly.toml app configuration file generated for music-links on 2024-10-15T13:10:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "music-links"
primary_region = "cdg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
